### ISSUE TITLE
Note on confidence measuring

### ISSUE THREAD

**Issue by erin-lea** [sidprasad/halp#1]
Hello! Couldn't find anywhere to just submit straight feedback so I figured opening an issue would do the trick. Firstly, I want to say that I think the idea of having a tool to summarize and answer questions on privacy policies is a great one that, if done well, could really help improve people's awareness of what data they are providing and what is being done with it. As I looked through your source code, I noticed that, when you pose these questions to ChatGPT, you ask it to respond with an answer and its confidence in said answer. I would caution against including this confidence measure. As you may know, ChatGPT can easily provide inaccurate information. I'm sure I could find some papers to support this if you would like. (Anecdotally, I once got it to say with full confidence that ["pecans played a crucial role during the [Cuban Missile] crisis"](https://chat.openai.com/share/bb4d85e5-f9bf-4763-a520-7174ba7d035a).) I also asked it to give me answers with confidence scores to questions about some news articles, attempting to emulate the formatting of your prompts ([link for your reference](https://chat.openai.com/share/83e38d5b-e5de-4de8-802b-29fb902c6667)). To be fair, it did give almost all correct answers, but it did say that someone was running for president with the Green Party when they really weren't with a confidence rating of .9. This was, of course, a smaller experiment, but I still think it's worth looking at.

Asking ChatGPT to measure confidence in its own answers may lead to HALP users misjudging ChatGPT's reading comprehension and trusting inaccurate information from the tool. The question, then, is how much risk of confident inaccurate answers you're willing to accept. Since the user is potentially making decisions about their privacy using information gained from this tool, I would be more conservative about this risk level. As an alternative to asking ChatGPT to declare its own confidence, it may be worth including some kind of disclaimer that ChatGPT can be prone to producing inaccurate information and that answers it gives should be verified before making any decisions based on them. Of course, you're free to keep it how it is if you wish, but I thought I would be remiss to not mention something when I saw it.

**Comment by sidprasad** [comment]
Thanks for the feedback and for checking out the project. Hopefully the PR above allays some of these concerns.
